# Generated by Django 3.2 on 2024-10-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genres',
            field=models.ManyToManyField(blank=True, through='reviews.TitleGenre', to='reviews.Genre', verbose_name='Жанр'),
        ),
    ]
