# Generated by Django 3.2 on 2024-10-01 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_title_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titlegenre',
            old_name='genre',
            new_name='genre_id',
        ),
        migrations.RenameField(
            model_name='titlegenre',
            old_name='title',
            new_name='title_id',
        ),
    ]
