# Generated by Django 3.2 on 2024-10-01 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20241001_1509'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TitleGenre',
            new_name='GenreTitle',
        ),
    ]
